/*
 * 创建日期 2007-12-25
 *
 * TODO 要更改此生成的文件的模板，请转至
 * 窗口 － 首选项 － Java － 代码样式 － 代码模板
 */
package com.website;

import java.io.StringReader;
import java.util.Hashtable;
import java.util.List;
import java.util.Random;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.input.SAXBuilder;

import com.beyondbit.web.form.PublishForm;
import com.beyondbit.web.form.TaskInfoForm;
import com.beyondbit.web.publishinfo.PublishOperate;
import com.component.database.CDataCn;
import com.component.database.CDataImpl;
import com.util.CBase64;
import com.util.CDate;
import com.util.CTools;

/**
 * @author panhao
 *
 * TODO 要更改此生成的类型注释的模板，请转至
 * 窗口 － 首选项 － Java － 代码样式 － 代码模板
 */
public class GetFInfo {
	
	private String info_title = "";						//标题
	private String info_content = "";					//内容
	private String info_createtime = "";				//创建时间
	private String info_subject_id = "";				//栏目id
	private String info_subject_name = "";				//栏目名
	private String info_sendunit = "";					//上传部门
	private String info_importantflag = "";				//导入标志
	private String [] filename ;						//文件名
	private String [] fileRealName ;					//实际文件名
	private String filePath = "";						//文件路径
	private String fileContent = "";					//附件内容
	private String path = com.beyondbit.web.publishinfo.Messages.getString("filepath");
	private String stateStr = "";						//接口运行状况 0 正常结束； 1 初始化时失败； 2 解析正文时失败；3 解析附件时失败；4 取附件信息时失败；
														//5 插入数据时失败； 6 取栏目id时失败； 7 删除时失败
	private String operateType = "";					//信息操作类型 0 新增；1 修改；2 删除
	private String ctId_old = "";
	static Random rand = new Random();

	/**
	 * 
	 * @description 初始化xml
	 * @param userXml xml的字符串
	 * @return xml的跟元素
	 */
	private Element initInfoData(String userXml) {
		//System.out.println("-------start init xml-----------");
		Element rootUserEle = null;
		try {
			Document doc = null;
			SAXBuilder sb = null;
			sb = new SAXBuilder();
			StringReader reader = new StringReader(userXml);
			doc = sb.build(reader, "GBK");
			rootUserEle = doc.getRootElement();
		} catch (Exception ex) {
			stateStr = "1";
			System.out.println(" XMLparseException::initInfoData(): "
					+ ex.getMessage());
		}
		//System.out.println("-------end init xml-----------");
		return rootUserEle;
	}
	
	/**
	 * 
	 * @description 解析xml
	 * @param parentEle 解析的xml元素
	 */
	private void getDataInfoStr(Element parentEle){
		//System.out.println("-------start parse xml-----------");
		String eleName = "";
		String eleValue = "";
		List eleList = null;
		Element subEle = null;
		int listlength = 0;
		try{
			if(parentEle != null){
				eleList = parentEle.getChildren();
				if(eleList != null){
					for (int count = 0; count < eleList.size(); count++) {
						subEle = (Element) eleList.get(count);
						eleName = subEle.getName();
						eleValue = subEle.getText();
						listlength = subEle.getChildren() != null ? subEle.getChildren().size() : 0;
						if(listlength > 0){
							if("FILEPUBATTACH".equals(eleName))
								getAttachAttr(subEle);
							else
								getDataInfoStr(subEle);
						}else{
							//map.put(eleName,eleValue);
							if("TITLE".equals(eleName))
								this.info_title = eleValue;
							
							else if("SUBJECTID".equals(eleName))
								this.info_subject_id = eleValue;
							
							else if("CONTENT".equals(eleName))
								this.info_content = eleValue;
							
							else if("FILEDATE".equals(eleName))
								this.info_createtime = eleValue;
							
							else if("SENDUNIT".equals(eleName))
								this.info_sendunit = eleValue;
							
							else if("IMPORTANTFLAG".equals(eleName))
								this.info_importantflag = eleValue;
							
							else if("OPERATE".equals(eleName))
								this.operateType = eleValue;
							
							else if("FORMID".equals(eleName))
								this.ctId_old = eleValue;
						}
					}
				}
			}
		}catch(Exception ex){
			stateStr = "2";
			System.out.println(ex.getMessage());
		}
		//System.out.println("-------end parse xml-----------");
	}
	
	/**
	 * 
	 * @description 得到附件
	 * @param attachEle 包含附件的xml元素
	 */
	private void getAttachAttr(Element attachEle){
		//System.out.println("-------start init attach xml-----------");
		List eleList = null;
		Element subEle = null;
		try{
			if(attachEle != null){
				eleList = attachEle.getChildren("PUBATTACH");
				if(eleList != null){
					filename = new String[eleList.size()];
					fileRealName = new String[eleList.size()];
					for(int count = 0; count < eleList.size(); count++){
						subEle = (Element) eleList.get(count);
						addAttachAttr(count,subEle);
					}
				}
			}
		}catch(Exception ex){
			stateStr = "3";
			System.out.println(ex.getMessage());
		}
		//System.out.println("-------end init attach xml-----------");
	}
	
	/**
	 * 
	 * @description 解析附件的属性
	 * @param cnt 附件的序列号
	 * @param attrEle 具体某一条附件的xml
	 */
	private void addAttachAttr(int cnt,Element attrEle){
		//System.out.println("-------start parse attach attribute xml-----------");
		String eleName = "";
		String eleValue = "";
		List eleList = null;
		Element subEle = null;
		String realName = "";
		String fileName = "";
		String fileExt = "";
		int listSize = 0;
		//create attach filepath
		String sToday = CDate.getThisday();
		int numeral = 0;
		numeral =(int)(Math.random()*100000);
		filePath = sToday + Integer.toString(numeral);
		java.io.File newDir = new java.io.File(path + filePath);
		if(!newDir.exists()) {
			newDir.mkdirs();
		}
		
		try{
			if(attrEle != null){
				eleList = attrEle.getChildren();
				listSize = eleList.size();
				if(eleList != null){
					for(int count = 0; count < listSize; count++){
						subEle = (Element) eleList.get(count);
						eleName = subEle.getName();
						eleValue = subEle.getText();
						if("FILENAME".equals(eleName))
							fileName = eleValue;
						else if("FILEEXTENSION".equals(eleName))
					    	fileExt = eleValue;
					    else if("FILECONTENT".equals(eleName))
					    	fileContent = eleValue;
					}
					realName = sToday + cnt + "." + fileExt;
				    filename[cnt] = fileName;
				    fileRealName[cnt] = realName;
				    
				    //save attach to file system
				    System.out.println(path + filePath + "\\\\" +fileRealName[cnt]);
					CBase64.saveDecodeStringToFile(fileContent,path + filePath + "\\\\" +fileRealName[cnt]);
				
				}
			}
		}catch(Exception ex){
			stateStr = "4";
			System.out.println(ex.getMessage());
		}
		//System.out.println("-------end parse attach attribute xml-----------");
	}
	
	/**
	 * 
	 * @description webservice 直接调用的方法
	 * @param BiztalkKey BiztalkKey
	 * @param BiztalkCode BiztalkCode
	 * @param Message 包含xml的字符串
	 * @return stateStr 解析的状态 0 正常结束； 1 初始化时失败； 2 解析正文时失败；3 解析附件时失败；4 取附件信息时失败；5 插入数据时失败； 6 取栏目id时失败
	 */
	public String GetInfoData(String BiztalkKey,String BiztalkCode,String Message)
    {
		try{
	        Element rootEle = initInfoData(Message);
	        getDataInfoStr(rootEle);
	        if("0".equals(operateType)){
	        	dealMessage();
	        }else if("1".equals(operateType)){
	        	deleteMessage(ctId_old);
	        	dealMessage();
	        }else if("2".equals(operateType)){
	        	deleteMessage(ctId_old);
	        }
	        	
	        dealMessage();
	        stateStr = "0";
		}catch(Exception ex){
			System.out.println(ex.getMessage());
		}
        return stateStr;
        
     }
	
	/**
	 * 
	 * @description 将信息插入到数据库
	 */
	private void dealMessage(){
		//System.out.println("-------start pdealMessage-----------");
		PublishForm publishform = new PublishForm();
		TaskInfoForm taskinfoform = new TaskInfoForm();
		PublishOperate operate = new PublishOperate();
		this.info_subject_name = getSubjectName(info_subject_id);
		try{
			taskinfoform.setTcMemo("");
			taskinfoform.setTcParentId("");
			taskinfoform.setTcPerson("4");
			//taskinfoform.setTcPersonName(""); 
			taskinfoform.setTcStatus("0");
			taskinfoform.seTcSenderId("");
			//taskinfoform.setPublishStatus("");
			taskinfoform.setTcTime(CDate.getNowTime());
			taskinfoform.setChkIDs("");
			
			publishform.setCtContent(info_content);
			publishform.setCtCreateTime(info_createtime);
			publishform.setCtFeedbackFlag("0");
			publishform.setCtFileFlag("0");
			publishform.setCtFocusFlag(info_importantflag);
			publishform.setCtInsertTime(CDate.getNowTime());
			publishform.setCtKeywords("");
			publishform.setCtSequence("100");
			publishform.setCtSource("[数据交换]"+info_sendunit);
			//publishform.setIsComment("0");
			publishform.setUpdateTime(CDate.getNowTime());
			publishform.setCtTitle(info_title);
			publishform.setCtUrl("");
			publishform.setCtImgPath("");
			publishform.setSjId(info_subject_id);
			publishform.setUrId("4");
			publishform.setDtId("107");
			publishform.setCtId("");
			publishform.setSjName(info_subject_name);
			publishform.setOrgSjId("");
			publishform.setContentFlag("0");
			
			//publishform.setPrimaryKey_id(operateType);
			
			publishform.setTaskInfoForm(taskinfoform);
			
			publishform.setFileRealName(filename);
			publishform.setFileList(fileRealName);
			publishform.setFilePath(filePath);
			
			operate.addNew(publishform);
			
		}catch(Exception e){
			stateStr = "5";
			System.out.println(e.getMessage());
		}
		//System.out.println("-------end pdealMessage-----------");
	}
	
	/**
	 * 删除报送的相关信息
	 * @param ct_id_old 报送信息的原id
	 * @return 删除是否成功 成功 true；失败 false
	 */
	private boolean deleteMessage(String ct_id_old){
		boolean flag = false;
		CDataCn dCn = null;
		CDataImpl dImpl = null;
		String sql = "select ct_id from tb_content where primarykey_id = '"+ ct_id_old +"'";
		Hashtable table = null;
		String ctId = "";
		try{
			dCn = new CDataCn();
			dImpl = new CDataImpl(dCn);
			table = dImpl.getDataInfo(sql);
			if(table != null){
				ctId = CTools.dealNull(table.get("ct_id"));
				dImpl.executeUpdate("delete from tb_content where ct_id = '"+ ctId +"'");
				dImpl.executeUpdate("delete from tb_contentdetail where ct_id = '"+ ctId +"'");
				dImpl.executeUpdate("delete from tb_contentpublish where ct_id = '"+ ctId +"'");
				dImpl.executeUpdate("delete from tb_image where ct_id = '"+ ctId +"'");
				flag = true;
			}
		
		}catch(Exception e){
			stateStr = "7";
			System.out.println(e.getMessage());
		}finally{
			dImpl.closeStmt();
			dCn.closeCn();
		}
		return flag;
	}
	
	/**
	 * 
	 * @description 得到栏目id
	 * @param subjectid 栏目id
	 * @return sjName 栏目名
	 */
	private String getSubjectName(String subjectid){
		
		CDataCn dCn = null;
		CDataImpl dImpl = null;
		String sjName = "";
		try{
			dCn = new CDataCn();
			dImpl = new CDataImpl(dCn);
			if(!subjectid.equals("")){
				String sqlStr = "select sj_name from tb_subject where sj_id = " + subjectid;
				Hashtable content = dImpl.getDataInfo(sqlStr);
				if(content!=null){
					sjName = CTools.dealNull(content.get("sj_name"));
				}
			}
		}catch(Exception e){
			stateStr = "6";
			System.out.println(e.getMessage());
		}finally{
			dImpl.closeStmt();
			dCn.closeCn();
		}
		
		return sjName;
	}
	
//	public static void main(String args[]){
//		GetFInfo f = new GetFInfo();
//		String testMessage = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
//		testMessage += "<DEP_DataExchangeData>";
//		testMessage += "<OperationType>消息发起</OperationType>";
//		testMessage += "<MessageTitle></MessageTitle>";
//		testMessage += "<MessageID>1.135.238.2007.33311</MessageID>";
//		testMessage += "<MessageBody><!-- 消息体-->";
//		testMessage += "<ROOT>";
//		testMessage += "<DATASEND>";
//		testMessage += "<TITLE>数据交换测试</TITLE> <!-- 标题-->";
//		testMessage += "<SUBJECTID>26404</SUBJECTID><!-- 栏目ID-->";
//		testMessage += "<SUBJECTNAME>sjb1</SUBJECTNAME><!-- 栏目名称-->";
//		testMessage += "<CONTENT>测试内容</CONTENT><!-- 内容 -->";
//		testMessage += "<FILEDATE>2007-05-15</FILEDATE><!-- 收发文日期 -->";
//		testMessage += "<SENDDATE>2007-05-15</SENDDATE><!-- 发送日期 -->";
//		testMessage += "<SENDUNIT>互联网公司</SENDUNIT><!-- 发送单位 -->";
//		testMessage += "<FILECODE></FILECODE><!-- 收发文编号 -->";
//		testMessage += "<IMPORTANTFLAG>1</IMPORTANTFLAG><!-- 重要提醒 1重要 0不重要-->";
//		testMessage += "<FILEPUBATTACH> <!-- 附件 -->";
//		testMessage += "<PUBATTACH> <!-- 多附件循环 -->";
//		testMessage += "<FILENAME>0_月度办法_1</FILENAME> <!-- 附件名称 -->";
//		testMessage += "<FILETYPE>application/msword</FILETYPE><!-- 附件类型 -->";
//		testMessage += "<FILELENGTH>21000</FILELENGTH><!-- 附件大小 -->";
//		testMessage += "<FILECONTENT>0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAANQAAAAAAAAAAEAAANwAAAAEAAAD+////AAAAADQAAAD////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////spcEAcWAJBAAA8FK/AAAAAAAAEAAAAAAABgAAABgAAA4AYmpianFQcVAAAAAAAAAAAAAAAAAAAAAAAAAECBYAMhwAABM6AQATOgEA3gMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//w8AAAAAAAAAAAD//w8AAAAAAAAAAAD//w8AAAAAAAAAAAAAAAAAAAAAAKQAAAAAAHoDAAAAAAAAegMAAHoDAAAAAAAAegMAAAAAAAB6AwAAAAAAAHoDAAAAAAAAegMAABQAAAAAAAAAAAAAAI4DAAAAAAAANgkAAAAAAAA2CQAAAAAAADYJAAAAAAAANgkAABwAAABSCQAAFAAAAI4DAAAAAAAAgBQAACIBAAByCQAAAAAAAHIJAAAAAAAAcgkAAAAAAAByCQAAAAAAAHIJAAAAAAAATQoAAAAAAABNCgAAAAAAAE0KAAAAAAAA8xMAAAIAAAD1EwAAAAAAAPUTAAAAAAAA9RMAAAAAAAD1EwAAAAAAAPUTAAAAAAAA9RMAACQAAACiFQAAaAIAAAoYAABmAAAAGRQAACEAAAAAAAAAAAAAAAAAAAAAAAAAegMAAAAAAAA3CwAAAAAAAAAAAAAAAAAAAAAAAAAAAABNCgAAAAAAAE0KAAAAAAAANwsAAAAAAAA3CwAAAAAAABkUAAAAAAAAAAAAAAAAAAB6AwAAAAAAAHoDAAAAAAAAcgkAAAAAAAAAAAAAAAAAAHIJAADbAAAAOhQAABYAAADzDQAAAAAAAPMNAAAAAAAA8w0AAAAAAAA3CwAAxgEAAHoDAAAAAAAAcgkAAAAAAAB6AwAAAAAAAHIJAAAAAAAA8xMAAAAAAAAAAAAAAAAAAPMNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANwsAAAAAAADzEwAAAAAAAAAAAAAAAAAA8w0AAAAAAADzDQAAOgAAAOcSAAAsAAAAegMAAAAAAAB6AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbxMAAAAAAAByCQAAAAAAAGYJAAAMAAAA8OZUFddFyAEAAAAAAAAAADYJAAAAAAAA/QwAAGoAAAATEwAACgAAAAAAAAAAAAAA8xMAAAAAAABQFAAAMAAAAIAUAAAAAAAAHRMAAFIAAABwGAAAAAAAAGcNAAB2AAAAcBgAABQAAABvEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAYAAAAAAAAAAAAAAAAAAB6AwAAAAAAAG8TAACEAAAATQoAABQAAABhCgAADgAAAPMNAAAAAAAAbwoAAAwAAAB7CgAAvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATQoAAAAAAABNCgAAAAAAAE0KAAAAAAAAGRQAAAAAAAAZFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Q0AABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE0KAAAAAAAATQoAAAAAAABNCgAAAAAAAIAUAAAAAAAANwsAAAAAAAA3CwAAAAAAADcLAAAAAAAANwsAAAAAAAAAAAAAAAAAAI4DAAAAAAAAjgMAAAAAAACOAwAAJAMAALIGAACEAgAAjgMAAAAAAACOAwAAAAAAAI4DAAAAAAAAsgYAAAAAAACOAwAAAAAAAI4DAAAAAAAAjgMAAAAAAAB6AwAAAAAAAHoDAAAAAAAAegMAAAAAAAB6AwAAAAAAAHoDAAAAAAAAegMAAAAAAAD/////AAAAAAIADAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIAMAAwADcALQAxADIALQAyADQAIAA6AA0ACP8OVPBTCf8NAEgAdABtAGwARwBlAG4AZQByAGEAdABlACAALwAgAEMAcgBlAGEAdABlAFcAZQBiAFMAdQBiAGoAZQBjAHQALgBhAHMAcAB4ACAAz2Pwjxr/uXD7UQBfy1kNTuqBqFI3UrBlhHZCAHUAZwANAGgAZQBhAGQALgBhAHMAYwB4ACAAz2Pwjxr/nligUiAAVVwAXzZlKX+MVFVcAF8gAO9TKFfbj0yIIADhT29g0VMDXoR29mUZUCAAqYvmXadPNmUpfxZiBYBVXABfDP/YnqSLhHbFYLVRC04gAC9mIAA2ZSl/tnIBYBv/DQBIAHQAbQBsAEcAZQBuAGUAcgBhAHQAZQAgAC8AIABDAHIAZQBhAHQAZQBXAGUAYgBTAHUAYgBqAGUAYwB0AC4AYQBzAHAAeAAgAM9j8I8a/7lw+1EAX8tZDU7qgahSN1KwZYR2QgB1AGcADQBWAGkAbgBkAGkAYwBhAHQAZQBBAGYAZgBhAGkAcgAgAC8AIABBAGQAZABNAGEAaQBsAGIAbwB4AFcAaQB0AGgAbwB1AHQARgByAGEAbQBlAC4AYQBzAHAAeAAgAM9j8I8a/y9lAWP5W2ZOsIvhT7F7hHb7baBSCP9QAFMAGv8PaO52xV97mC9mIABmTrCL4U+xewn/G/8NAFYAaQBuAGQAaQBjAGEAdABlAEEAZgBmAGEAaQByACAALwAgAEUAZABpAHQATQBhAGkAbABiAG8AeAAuAGEAcwBwAHgALgBhAHMAcAB4ACAAz2Pwjxr/L2UBY/lbZk6wi+FPsXuEdu5POWUI/1AAUwAa/w9o7nbFX3uYL2YgAGZOsIvhT7F7Cf8b/w0ADQAI/01S8FMJ/wdZ6Gwa/ztOgYkvZvlbIACGmPxb4U+xe4R2IAAYTxZTIACMVAz/+VuQX0ds4U+/i9Bjm0+EdgBOm051mGKXDQB3AGEAcgBkAGUAbgBtAGEAaQBsAC8AIABBAHAAcABlAGEAbABJAG4AZgBvAC4AYQBzAHAAeAAgAM9j8I8a//lbSgBzABqBLGfbj0yIKX/PUQIw334AToljAE4qTmoAcwCTXsyRYpeEdhqBLGcCMH1ZBFkvZhr/dZhilydZD1wpf89RIAAxADAAJQAgAKBS619PbciJH5CmXoxU9H6kYidgAjANAGEAcABwAGUAYQBsAFwAQQBwAHAAZQBhAGwASQBuAGYAbwAuAGEAcwBwAHgAIADPY/CPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAGggAACIIAAAkCAAAPAgAAEIIAABsCAAAbggAAHIIAAB0CAAAkAgAAKIIAACkCAAAqAgAAKoIAADACAAADAkAACQJAAAqCQAAVAkAAFYJAABaCQAAdgkAAHgJAACWCQAAnAkAAMgJAADSCQAA1AkAANgJAADaCQAADgoAABAKAAAuCgAANAoAAFQKAABeCgAAYAoAAGQKAACaCgAApgoAAPr1+u767vrk3/rY3+Tf087H38ff5N/1wLutprucu5e7kIt6c4tpi/UAAAAAAAASFWgbfcgAFmhACecANQiBbygBAAwVaE1OqAAWaEAJ5wAAIBVoQAnnABZoQAnnAENKEgBLSAAAT0oDAFBKAwBhShIAAAkWaEAJ5wBvKAEMFWhFHBgAFmhACecAAAkWaCkpLABvKAESFWgbfcgAFmhFHBgANQiBbygBAAwVaE1OqAAWaEUcGAAAGhZoKSksAENKEgBLSAAAT0oDAFBKAwBhShIAAAkWaEUcGABvKAEMFWhFHBgAFmhFHBgAAAwVaE1OqAAWaBt9yAAACRZoMGasAG8oAQkWaNZnxgBvKAEMFWjWZ8YAFmjWZ8YAAAkWaBt9yABvKAESFWgbfcgAFmgbfcgANQiBbygBAAwVaE1OqAAWaE1OqAAACRZoKy8JAG8oAQkWaE1OqABvKAEAKAAGAAAaCAAAJAgAAJAIAAAMCQAAeAkAABAKAACcCgAAngoAAOYKAACKCwAAaBQAAAoVAACoFQAARBYAAPoWAAD8FgAA/hYAACgXAABYFwAAiBcAAKoXAAD9AAAAAAAAAAAAAAAA/QAAAAAAAAAAAAAAAPUAAAAAAAAAAAAAAADtAAAAAAAAAAAAAAAA5QAAAAAAAAAAAAAAAN0AAAAAAAAAAAAAAADlAAAAAAAAAAAAAAAA2AAAAAAAAAAAAAAAANgAAAAAAAAAAAAAAADQAAAAAAAAAAAAAAAAyAAAAAAAAAAAAAAAAMgAAAAAAAAAAAAAAADIAAAAAAAAAAAAAAAAyAAAAAAAAAAAAAAAAMgAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAwwAAAAAAAAAAAAAAAMMAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAuAAAAAAAAAAAAAAAALgAAAAAAAAAAAAAAAAAAAAAAAAAAAoAABGEZwBXRDEAYIRnAGdk1z51AAAEAABnZEAnmQAIAAAKJgALRgIAZ2Thct8ACAAACiYAC0YCAGdkPDBSAAAEAABnZCsvCQAIAAAKJgALRgEAZ2QpKSwACAAACiYAC0YBAGdkKy8JAAgAAAomAAtGAQBnZDBmrAAIAAAKJgALRgEAZ2RNTqgAAAEAAAAVAAYAAAAYAAD9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAABAQGmCgAAqgoAAOQKAADmCgAA+goAAP4KAAAcCwAAHgsAACILAAAkCwAAhgsAAIgLAACKCwAAtgsAALgLAAC8CwAAABQAAGYUAABoFAAAnBQAAJ4UAACiFAAAChUAADoVAAA8FQAAQBUAAKgVAADWFQAA2BUAANwVAABEFgAAjBYAAI4WAACSFgAA+hYAAP4WAAAaFwAAHhcAACAXAAAmFwAAKBcAAFQXAABYFwAA9vHp4t3i2M7d2MnYu7asqralu7astru2rLa7tqy2u7astp6UjYaNnnhtAAAAABUWaEAnmQA1CIFCKg1vKAFwaJkzAAAbFWhAJ5kAFmhAJ5kANQiBQioNbygBcGiZMwAADBZouRZQADUIgW8oAQAMFmhAJ5kANQiBbygBABIVaEAnmQAWaEAnmQA1CIFvKAEADBZo1z51ADUIgW8oAQAJFmgrLwkAbygBA1UIARIVaBt9yAAWaOFy3wA1CIFvKAEACRZo4XLfAG8oARoWaAx5XQBDShIAS0gAAE9KAwBQSgMAYUoSAAAJFmg8MFIAbygBEhVoG33IABZoG33IADUIgW8oAQAJFmgDV4UAbygBCRZoG33IAG8oAQwVaANXhQAWaANXhQAADxVoX252ABZoU1LvAG8oAQkWaGZmRQBvKAESFWhmZkUAFmhmZkUANQiBbygBKhr/+VtKAHMAGoEsZ9uPTIgpf89RAjDffgBOiWMATipOagBzAJNezJFil4R2GoEsZwIwfVkEWS9mGv91mGKXJ1kPXCl/z1EgADEAMAAlACAAoFLrX09tyIkfkKZejFT0fqRiJ2ACMA0AYwBvAG4AbgBlAGMAdABpAG8AbgBcAE0AYQBpAGwAYgBvAHgATwBuAGUALgBhAHMAcAB4ACAAz2Pwjxr/+VtKAHMAGoEsZ9uPTIgpf89RAjDffgBOiWMATipOagBzAJNezJFil4R2GoEsZwIwfVkEWS9mGv91mGKXJ1kPXCl/z1EgADEAMAAlACAAoFLrX09tyIkfkKZejFT0fqRiJ2ACMA0AZQB2AGEAbAB1AGEAdABlAFwAQQBwAHAAZQBhAGwASQBuAGYAbwAuAGEAcwBwAHgAIADPY/CPGv/5W0oAcwAagSxn249MiCl/z1ECMN9+AE6JYwBOKk5qAHMAk17MkWKXhHYagSxnAjB9WQRZL2Ya/3WYYpcnWQ9cKX/PUSAAMQAwACUAIACgUutfT23IiR+Qpl6MVPR+pGInYAIwDQBnAGUAbgBlAHIAYQBsAFwAQQBwAHAAZQBhAGwASQBuAGYAbwAuAGEAcwBwAHgAIADPY/CPGv/5W0oAcwAagSxn249MiCl/z1ECMN9+AE6JYwBOKk5qAHMAk17MkWKXhHYagSxnAjB9WQRZL2Ya/3WYYpcnWQ9cKX/PUSAAMQAwACUAIACgUutfT23IiR+Qpl6MVPR+pGInYAIwDQB3AGEAcgBkAGUAbgBtAGEAaQBsAFwAQQBwAHAAZQBhAGwASQBuAGYAbwBMAGUAYQBkAGUAcgBNAGEAaQBsAC4AYQBzAHAAeAAgAM9j8I8a//lbSgBzABqBLGfbj0yIKX/PUQIw334AToljAE4qTmoAcwCTXsyRYpeEdhqBLGcCMH1ZBFkvZhr/dZhilydZD1wpf89RIAAxADAAJQAgAKBS619PbciJH5CmXoxU9H6kYidgAjANAA0ADQD7baBShHYATptOkF9HbOFPv4sAl4GJhHZ1mGKXIAD3iwt3h2VjaBr/DQAgAFF/Ck7hT7+LCP+VYsmLCf8tTsNfDk7olTdipE6STodlY2guAGQAbwBjACwADQAAl4GJzZGwZQBf0VOEdnWYYpdfADIAMAAwADcAMQAyADAANgAuAGQAbwBjACwADQCQX0ds6JU3YlF/FV/RU4R2+HZzUe6VmJguAGQAbwBjAA0ADQANACdZgmnuXQ1OGlkxXC9m2Y+bThxOf4mGTgIw71P9gNiPCWeIXxpZMFe5ZaFsmVHbj7tTAjARYj1cz5ECMLBzKFfqU/2A82AwUtmPm06GTg0ADQBYFwAAoBcAAKgXAACqFwAArBcAAP4XAAAAGAAA8ePZ1M/HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8VaE1OqAAWaE1OqABvKAEJFmjqYvIAbygBCRZoVXjxAG8oARIVaEAnmQAWaBNGzgA1CIFvKAEAGxVowXTfABZoQCeZADUIgUIqDW8oAXBomTMAABsVaNc+dQAWaEAnmQA1CIFCKg1vKAFwaJkzAAAABqoXAACsFwAArhcAAP4XAAAAGAAA+gAAAAAAAAAAAAAAAPoAAAAAAAAAAAAAAAD6AAAAAAAAAAAAAAAA9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAZ2QbfcgAAAQAAGdkWR7hAAAEMAAxkDgBMlACAB+wgi4gsMZBIbAIByKwCAcjkKAFJJCgBSWwAAAXsFMDGLDgAwyQqQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhgIPABIAAQCcAA8ABAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATgAAQPH/AgBOAAwEAAAAAAAAAAACAGNrh2UAAAsAAAADJAMxJABhJAMAJABDShUAS0gCAFBKBABfSAEEYUoYAG1ICQRuSAQIc0gJBHRIBAgAAAAAAAAAAAAAAAAAAAAAAAAkAEFA8v+hACQADAUAAAAAAAAAAAYA2J6ki7VrPYRXW1NPAAAAAEIAaUDz/7MAQgAMBQAAAAAAAAAABABuZhqQaIg8aAAAHAAX9gMAADTWBgABCgNsADTWBgABBQMAAGH2AwAAAgALAAAAIABrQPT/wQAgAAAFAAAAAAAAAAADAOBlF1JoiAAAAgAAAAAAAAAAAAAA3gMAABoAABwAABkA/////wAAAAANAAAAEgAAAEgAAACGAAAAvAAAAAgBAABOAQAATwEAAHMBAADFAQAAEgIAAGMCAACyAgAAAAMAAFsDAABcAwAAXQMAAHIDAACKAwAAogMAALMDAAC0AwAAtQMAAN0DAADgAwAAmAAAAAAwAAAAAAAAAIAAAACAAAAAAAAAAAAAAJgAAAAAMAAAAAAAAACAAAAAgAAAAAAAAAAAAACYAAEgADAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAABIAAwAQAAAAAAAIAAAACAAAAAAAAAAAAAAJgAASAAMAIAAAAAAACAAAAAgAAAAAAAAAAAAACYAAEgADADAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAABIAAwBAAAAAAAAIAAAACAAAAAAAAAAAAAAJgAAAAAMAAAAAAAAACAAAAAgAAAAAAAAAAAAACYAAAAADAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAACIAAwAAAAAAAAAIAAAACAAAAAAAAAAAAAAJgAAiAAMAEAAAAAAACAAAAAgAAAAAAAAAAAAACYAAIgADACAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAACIAAwAwAAAAAAAIAAAACAAAAAAAAAAAAAAJgAAiAAMAQAAAAAAACAAAAAgAAAAAAAAAAAAACYAAIgADAFAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAAAAAAwAAAAAAAAAIAAAACAAAAAAAAAAAAAAJgAAAAAMAAAAAAAAACAAAAAgAAAAAAAAAAAAACYAAAAADAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAAAAAAwAAAAAAAAAIAAAACAAAAAAAAAAAAAAJgAAAAAAAAAAAAAAACAAAAAgAAAAAAAAAAAAACYAAAAAAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAAAAAAwAAAAAAAAAIAAAACAAAAAAAAAAAAAAJgAAAAAMAAAAAAAAACAAAAAgAAAAAAAAAAAAACYAAAAADAAAAAAAAAAgAAAAIAAAAAAAAAAAAAHmAAAAAAwAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAANAAAAEgAAAEgAAACGAAAAvAAAAAgBAABOAQAATwEAAHMBAADFAQAAEgIAAGMCAACyAgAAAAMAAFsDAACKAwAAogMAALMDAADdAwAA4AMAAJgAAAAAMAAAAAAAAACAAAAAgAAAAAAAAAAAAACYAAAAADAAAAAAAAAAgAAAAIAAAAAAAAAAAIAAmAABIAAwAAAAAAAAAIAAAACAAAAAAAAAAAAAAJgAASAAMAEAAAAAAACAAAAAgAAAAAAAAAAAgACYAAEgADACAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAABIAAwAwAAAAAAAIAAAACAAAAAAAAAAAAAAJgAASAAMAQAAAAAAACAAAAAgAAAAAAAAAAAAACYAAAAADAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAmAAAAAAwAAAAAAAAAIAAAACAAAAAyAAAAACAAJgAAiAAMAAAAAAAAACAAAAAgAAAAMgAAAAAgACYAAIgADABAAAAAAAAgAAAAIAAAADIAAAAAIAAmAACIAAwAgAAAAAAAIAAAACAAAAAyAAAAACAAJgAAiAAMAMAAAAAAACAAAAAgAAAAMgAAAAAgACYAAIgADAEAAAAAAAAgAAAAIAAAADIAAAAAIAAmAACIAAwBQAAAAAAAIAAAACAAAAAyAAAAACAAJoAAiAAMAUAAAAAAACAAAAAgAAAAMgAAAAAgAeaAAIgADAFAAAAAAAAgAAAAIAAAADIAAAAAIAHmgACIAAwBQAAAAAAAIAAAACAAAAAyAAAAACAB5oAAiAAMAUAAAAAAACAAAAAgAAAAMgAAAAAgAeaQAEgADACAAAAAAAAgAAAAIAAAAAAAAAAAIAHAAYAAKYKAABYFwAAABgAAAYAAAAJAAAADAAAAAAGAACqFwAAABgAAAcAAAANAAAAAAYAAAAYAAAIAAAADwAA8DgAAAAAAAbwGAAAAAIIAAACAAAAAQAAAAEAAAABAAAAAgAAAEAAHvEQAAAA//8AAAAA/wCAgIAA9wAAEAAPAALwkgAAABAACPAIAAAAAQAAAAEEAAAPAAPwMAAAAA8ABPAoAAAAAQAJ8BAAAAAAAAAAAAAAAAAAAAAAAAAAAgAK8AgAAAAABAAABQAAAA8ABPBCAAAAEgAK8AgAAAABBAAAAA4AAFMAC/AeAAAAvwEAABAAywEAAAAA/wEAAAgABAMJAAAAPwMBAAEAAAAR8AQAAAABAAAA//8BAAAABgBl5EQACAACAGRLIwAAAAAA4AMAAAAAAAABAAoAAADgAwAAAAAAAAEAAAA7AAAAAQAAACqAdXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTpvZmZpY2U6c21hcnR0YWdzB4BjaHNkYXRlAIAMAAABcE38HAkAAAACgDEyBIAyMDA3AoAyNAOARGF5BYBGYWxzZQuASXNMdW5hckRhdGUJgElzUk9DRGF0ZQWATW9udGgEgFllYXIBAAUAAAAIAAAAAQAAAAcAAAAAAAAAAwAAAAIAAAAFAAAABAAAAAYAAAAEAAAAAAAAABIAAAAeAAAAIQAAADYAAABIAAAAUQAAAIYAAACSAAAAlQAAAKoAAACrAAAAuAAAALwAAADLAAAAzgAAAOkAAAAIAQAAFwEAABoBAAAvAQAAYQEAAGMBAABkAQAAcgEAAHMBAAB9AQAAfwEAAI4BAAChAQAAowEAAMwBAADbAQAA3AEAAN4BAADfAQAA4AEAAO4BAADwAQAAHQIAACwCAAAtAgAALwIAADACAAAxAgAAPwIAAEECAABsAgAAewIAAHwCAAB+AgAAfwIAAIACAACOAgAAkAIAALoCAADJAgAAygIAAMwCAADNAgAAzgIAANwCAADeAgAAAAMAACQDAAAlAwAAJwMAACgDAAApAwAANwMAADkDAABzAwAAhAMAALUDAADcAwAA4AMAAAcAHAAHABwABwAcAAcAHAAHABwABwAFAAcAHAAHABwABwAcAAcAHAAHAAUABwAFAAcAHAAHABwABwAcAAcAHAAHAAUABwAFAAcAHAAHABwABwAFAAcABQAHABwABwAcAAcABQAHAAUABwAcAAcAHAAHAAUABwAFAAcAHAAHABwABwAFAAcABQAHABwABwAFAAcABAAHAAAAAAAIAAAADAAAAD4AAAA/AAAAsgAAALMAAACFAwAAiAMAAJ0DAACgAwAApAMAAKcDAACvAwAAsgMAANMDAADdAwAA4AMAAAcAMwAHAHMABwBzAAcAMwAHADMABwAzAAcAMwAHAAQABwAAAAAASAAAAIYAAAC7AAAAcwEAAJwBAADFAQAA6QEAABICAAA6AgAAYwIAAIkCAACyAgAA1wIAAAADAAAyAwAAzwMAANMDAADcAwAA4AMAAAUABwAFAAcABQAHAAUABwAFAAcABQAHAAUABwAFAAcABQAEAAcAAAAAALUDAADcAwAA4AMAAAcABAAHAAIAxk2HONZWAK3/D/8P/w//D/8P/w//D/8P/w8QAEQRkXX0E6pF/w//D/8P/w//D/8P/w//D/8PEAABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAADGAAAD4RoARGEmP4VxgUAAWgBBl6EaAFghJj+bygAAgAAAC4AAQAAAASAAQAAAAAAAAAAAAAAAAAAAAAAChgAAA+ESAMRhFz+FcYFAAFIAwZehEgDYIRc/odoAAAAAIhIAAACAAEAKQABAAAAAoIBAAAAAAAAAAAAAAAAAAAAAAAKGAAAD4TsBBGEXP4VxgUAAewEBl6E7ARghFz+h2gAAAAAiEgAAAIAAgAuAAEAAAAAgAEAAAAAAAAAAAAAAAAAAAAAAAoYAAAPhJAGEYRc/hXGBQABkAYGXoSQBmCEXP6HaAAAAACISAAAAgADAC4AAQAAAASAAQAAAAAAAAAAAAAAAAAAAAAAChgAAA+ENAgRhFz+FcYFAAE0CAZehDQIYIRc/odoAAAAAIhIAAACAAQAKQABAAAAAoIBAAAAAAAAAAAAAAAAAAAAAAAKGAAAD4TYCRGEXP4VxgUAAdgJBl6E2AlghFz+h2gAAAAAiEgAAAIABQAuAAEAAAAAgAEAAAAAAAAAAAAAAAAAAAAAAAoYAAAPhHwLEYRc/hXGBQABfAsGXoR8C2CEXP6HaAAAAACISAAAAgAGAC4AAQAAAASAAQAAAAAAAAAAAAAAAAAAAAAAChgAAA+EIA0RhFz+FcYFAAEgDQZehCANYIRc/odoAAAAAIhIAAACAAcAKQABAAAAAoIBAAAAAAAAAAAAAAAAAAAAAAAKGAAAD4TEDhGEXP4VxgUAAcQOBl6ExA5ghFz+h2gAAAAAiEgAAAIACAAuAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAMYAAAPhGgBEYSY/hXGBQABaAEGXoRoAWCEmP5vKAACAAAALgABAAAABIABAAAAAAAAAAAAAAAAAAAAAAAKGAAAD4RIAxGEXP4VxgUAAUgDBl6ESANghFz+h2gAAAAAiEgAAAIAAQApAAEAAAACggEAAAAAAAAAAAAAAAAAAAAAAAoYAAAPhOwEEYRc/hXGBQAB7AQGXoTsBGCEXP6HaAAAAACISAAAAgACAC4AAQAAAACAAQAAAAAAAAAAAAAAAAAAAAAAChgAAA+EkAYRhFz+FcYFAAGQBgZehJAGYIRc/odoAAAAAIhIAAACAAMALgABAAAABIABAAAAAAAAAAAAAAAAAAAAAAAKGAAAD4Q0CBGEXP4VxgUAATQIBl6ENAhghFz+h2gAAAAAiEgAAAIABAApAAEAAAACggEAAAAAAAAAAAAAAAAAAAAAAAoYAAAPhNgJEYRc/hXGBQAB2AkGXoTYCWCEXP6HaAAAAACISAAAAgAFAC4AAQAAAACAAQAAAAAAAAAAAAAAAAAAAAAAChgAAA+EfAsRhFz+FcYFAAF8CwZehHwLYIRc/odoAAAAAIhIAAACAAYALgABAAAABIABAAAAAAAAAAAAAAAAAAAAAAAKGAAAD4QgDRGEXP4VxgUAASANBl6EIA1ghFz+h2gAAAAAiEgAAAIABwApAAEAAAACggEAAAAAAAAAAAAAAAAAAAAAAAoYAAAPhMQOEYRc/hXGBQABxA4GXoTEDmCEXP6HaAAAAACISAAAAgAIAC4AAgAAAEQRkXUAAAAAAAAAAAAAAADGTYc4AAAAAAAAAAAAAAAA/////////////wIAAAAAAAAA//8CAAAAEgCgZNRxGQAJBBsACQQPAAkEGQAJBBsACQQPAAkEGQAJBBsACQQSAK7FBBgZAAkEGwAJBA8ACQQZAAkEGwAJBA8ACQQZAAkEGwAJBBsAAAAEAAAACAAAAOUAAAAAAAAAGgAAACsvCQBFHBgAKSksAGZmRQC5FlAAPDBSANQZVgAMeV0AEg1lAJdgcADXPnUAX252AANXhQBAJ5kATU6oADBmrAAiWMMA1mfGABt9yAATRs4A4XLfAMF03wBZHuEAQAnnAFNS7wBVePEA6mLyAP9AA4ABANwDAADcAwAAIC1LAQEAAQDcAwAAAAAAANwDAAAAAAAAAhwAAAAAAAAA3gEAAN4DAACgAQAIAAAAAKABABQAAAAA//8BAAAABwBVAG4AawBuAG8AdwBuAP//AQAIAAAAAAAAAAAAAAD//wEAAAAAAP//AAACAP//AAAAAP//AAACAP//AAAAAAUAAABHFpABAAACAgYDBQQFAgMEh3oAIAAAAIAIAAAAAAAAAP8BAAAAAAAAVABpAG0AZQBzACAATgBlAHcAIABSAG8AbQBhAG4AAAA1FpABAgAFBQECAQcGAgUHAAAAAAAAABAAAAAAAAAAAAAAAIAAAAAAUwB5AG0AYgBvAGwAAAAzJpABAAACCwYEAgICAgIEh3oAIAAAAIAIAAAAAAAAAP8BAAAAAAAAQQByAGkAYQBsAAAALzWQAYYAAgEGCQMBAQEBAQMAAAAAAA4IEAAAAAAAAAABAAQAAAAAALBli1tTTwAAOwaQAYYDAgEGAAMBAQEBAQMAAAAAAA4IEAAAAAAAAAABAAQAAAAAAItbU08AAFMAaQBtAFMAdQBuAAAAIAAEADEIiBgAAKQBAABoAQAAAACMwrwmrcK8JgAAAAAmACEAAACTAAAASwMAAAEAAQAAAAQAAxAHAAAAkwAAAEsDAAABAAEAAAAHAAAAAAAAAHEDAAAAAAAAAwAtABMAIQApACwALgA6ADsAPwBdAH0AqAC3AMcCyQIVIBYgGSAdICYgNiIBMAIwAzAFMAkwCzANMA8wETAVMBcwAf8C/wf/Cf8M/w7/Gv8b/x//Pf9A/1z/Xf9e/+D/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAWwB7ALcAGCAcIAgwCjAMMA4wEDAUMBYwCP8O/zv/W//h/+X/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgHoAW0AJwAgoASBAAAEAAZAGQAAAAZAAAA3QMAAN0DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAACDKDUQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIUAAAAAAJ8P8PAQABPwAAqAMAAP///3////9/////f////3////9/////f////39NTqgAAAAAADIAAAAAAAAAAAAAAAAAAAAAAP//EgAAAAAAAAAMADIAMAAwADcALQAxADIALQAyADQAIAA6AAAAAAAAAAkAbABpAHUAagB1AG4AeAB1AG4ACQBsAGkAdQBqAHUAbgB4AHUAbgAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAGAAAAAgAAAAAADAABAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+/wAABQICAAAAAAAAAAAAAAAAAAAAAAABAAAA4IWf8vlPaBCrkQgAKyez2TAAAACAAQAAEQAAAAEAAACQAAAAAgAAAJgAAAADAAAAsAAAAAQAAAC8AAAABQAAANAAAAAGAAAA3AAAAAcAAADoAAAACAAAAPwAAAAJAAAAEAEAABIAAAAcAQAACgAAADwBAAAMAAAASAEAAA0AAABUAQAADgAAAGABAAAPAAAAaAEAABAAAABwAQAAEwAAAHgBAAACAAAAqAMAAB4AAAAQAAAAMjAwNy0xMi0yNCA6AAAAAB4AAAAEAAAAAAAAAB4AAAAMAAAAbGl1anVueHVuAAAAHgAAAAQAAAAAAAAAHgAAAAQAAAAAAAAAHgAAAAwAAABOb3JtYWwuZG90AAAeAAAADAAAAGxpdWp1bnh1bgAAAB4AAAAEAAAAMzgAAB4AAAAYAAAATWljcm9zb2Z0IE9mZmljZSBXb3JkAAAAQAAAAAAGLJwEAAAAQAAAAADY2F3SRcgBQAAAAADeBPrWRcgBAwAAAAEAAAADAAAAkwAAAAMAAABLAwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v8AAAUCAgAAAAAAAAAAAAAAAAAAAAAAAQAAAALVzdWcLhsQk5cIACss+a4wAAAArAAAAAoAAAABAAAAWAAAAA8AAABgAAAABQAAAGwAAAAGAAAAdAAAABEAAAB8AAAAFwAAAIQAAAALAAAAjAAAABAAAACUAAAAEwAAAJwAAAAWAAAApAAAAAIAAACoAwAAHgAAAAQAAAAAAAAAAwAAAAcAAAADAAAAAQAAAAMAAADdAwAAAwAAAOYVCwALAAAAAAAAAAsAAAAAAAAACwAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0AAAAOAAAA/v///xAAAAARAAAAEgAAABMAAAAUAAAAFQAAABYAAAD+////GAAAABkAAAAaAAAAGwAAABwAAAAdAAAAHgAAAB8AAAAgAAAAIQAAACIAAAAjAAAA/v///yUAAAAmAAAAJwAAACgAAAApAAAAKgAAACsAAAD+////LQAAAC4AAAAvAAAAMAAAADEAAAAyAAAAMwAAAP7////9////NgAAAP7////+/////v//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////UgBvAG8AdAAgAEUAbgB0AHIAeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYABQH//////////wMAAAAGCQIAAAAAAMAAAAAAAABGAAAAAAAAAAAAAAAA4BJcFddFyAE4AAAAgAAAAAAAAABEAGEAdABhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgACAf///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAEAAAAAAAADEAVABhAGIAbABlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAIBAQAAAAYAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAIQYAAAAAAAAVwBvAHIAZABEAG8AYwB1AG0AZQBuAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoAAgECAAAABQAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMhwAAAAAAAAFAFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAACAf///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAEAAAAAAAAAUARABvAGMAdQBtAGUAbgB0AFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAA4AAIBBAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAQAAAAAAAAAQBDAG8AbQBwAE8AYgBqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAgD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAD+////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AQD+/wMKAAD/////BgkCAAAAAADAAAAAAAAARhsAAABNaWNyb3NvZnQgT2ZmaWNlIFdvcmQgzsS1tQAKAAAATVNXb3JkRG9jABAAAABXb3JkLkRvY3VtZW50LjgA9DmycQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</FILECONTENT> <!-- 附件内容 -->";
//		testMessage += "<FILEEXTENSION>doc</FILEEXTENSION><!-- 附件扩展名 -->";
//		testMessage += "</PUBATTACH>";
//		testMessage += "<PUBATTACH>";
//		testMessage += "<FILENAME>0_月度办法_2</FILENAME>";
//		testMessage += "<FILETYPE>application/msword</FILETYPE>";
//		testMessage += "<FILELENGTH>21000</FILELENGTH>";
//		testMessage += "<FILECONTENT>0M8R4KGxGAAAAAA==</FILECONTENT>";
//		testMessage += "<FILEEXTENSION>doc</FILEEXTENSION>";
//		testMessage += "</PUBATTACH>";
//		testMessage += "<PUBATTACH>";
//		testMessage += "<FILENAME>0_月度办法_3</FILENAME>";
//		testMessage += "<FILETYPE>application/msword</FILETYPE>";
//		testMessage += "<FILELENGTH>21000</FILELENGTH>";
//		testMessage += "<FILECONTENT>0M8R4KGxGAAAAAA==</FILECONTENT>";
//		testMessage += "<FILEEXTENSION>doc</FILEEXTENSION>";
//		testMessage += "</PUBATTACH>";
//		testMessage += "</FILEPUBATTACH>";
//		testMessage += "</DATASEND>";
//		testMessage += "</ROOT>";
//		testMessage += "</MessageBody>";
//		testMessage += "<SourceUnitCode></SourceUnitCode>";
//		testMessage += "<SourceCaseCode></SourceCaseCode>";
//		testMessage += "<DestUnit>";
//		testMessage += "<DestUnitCode></DestUnitCode>";
//		testMessage += "<DestCaseCode></DestCaseCode>";
//		testMessage += "<InterFaceCode></InterFaceCode>";
//		testMessage += "</DestUnit>";
//		testMessage += "<Sender></Sender>";
//		testMessage += "<SendTime>15:44</SendTime>";
//		testMessage += "<EndTime>2007-12-7 15:44:13</EndTime>";
//		testMessage += "</DEP_DataExchangeData>";
//		f.dealMessage(testMessage);
//	}
}