package com.weixin;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

public class WeChatServlet extends HttpServlet{
	private Logger logger;
	private String returnStr;
	/**
	 * 
	 */
    public WeChatServlet()
    {
    }
    /**
     * init·½·¨
     */
    public void init()
        throws ServletException
    {
        logger = Logger.getLogger(com.weixin.WeChatServlet.class);
    }
    /**
     * 
     * @param request
     * @param response
     * @throws ServletException
     * @throws IOException
     */
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		response.setContentType("text/json; charset=utf-8");
		response.setHeader("Access-Control-Allow-Origin", "*");
		PrintWriter out = response.getWriter();
		
		WeChatController wc = new WeChatController();
		Map<String, String> wechatParam=wc.getWechatParam(request.getParameter("url"));
		//System.out.println("url=================="+request.getParameter("url"));
		JSONArray jsonarray = new JSONArray();  
		JSONObject jsonobj = new JSONObject(); 
		//Æ´json
    	for (Map.Entry entry : wechatParam.entrySet()) {
    		jsonobj.put(entry.getKey().toString(), entry.getValue()); 
    		//System.out.println("key=="+entry.getKey().toString()+"===values=="+entry.getValue());
    	}
    	jsonarray.add(jsonobj);
    	 
    	
    	out = response.getWriter();
    	out.print(jsonarray);
    	out.flush();
    	out.close();
	}
	/**
	 * 
	 * @param request
	 * @param response
	 * @throws ServletException
	 * @throws IOException
	 */
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz
		doGet(request, response);
	}
}
