/*
 * Created on 2004-9-7
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.beyondbit.soft2.onlinework;

import java.io.IOException;
import java.io.OutputStream;
import java.io.BufferedWriter;
import java.io.OutputStreamWriter;
import java.util.Hashtable;
import java.util.Iterator;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.xpath.XPathResult;

import com.component.database.*;
import com.beyondbit.soft2.utils.*;
;

/**
 * @author along
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
public class WSBServlet extends HttpServlet {

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz

		CDataCn dCn = new CDataCn();
		CDataImpl dImpl = new CDataImpl(dCn);

		String wo_id = request.getParameter("wo_id");
		String pr_id = request.getParameter("pr_id");
		Hashtable xmlTable = null;

		Document doc = null;


		if (wo_id == null || wo_id.equals("")) {
			// 空表单
			xmlTable = dImpl.getDataInfo("select owt1_id, owt1_xml, owt2_xsl from tb_onlineworkxmltype xml, tb_onlineworkxsltype xsl where xml.owt2_id=xsl.owt2_id and xml.pr_id='" + pr_id + "'");
			if (xmlTable != null) {
				String owt1_id = xmlTable.get("owt1_id").toString();
				String owt1_xml = xmlTable.get("owt1_xml").toString();
				String owt2_xsl = xmlTable.get("owt2_xsl").toString();
				//doc = XMLUtil.string2Doc(owt1_xml);
			} else {
				return;
			}
		} else {
			// 修改表单
			xmlTable = dImpl.getDataInfo("select ow_id, ow_content from tb_onlinework where tb_onlinework.wo_id='" + wo_id + "'");
			String ow_id = xmlTable.get("ow_id").toString();
			String ow_content = xmlTable.get("ow_content").toString();
			//doc = XMLUtil.string2Doc(ow_content);
		}

		if (doc != null) {
			BufferedWriter out = new BufferedWriter(new OutputStreamWriter(response.getOutputStream()));

			out.write("<html>");
			out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">");
			out.write("<HTML>");
			out.write("<HEAD>");
			out.write("<TITLE> 因公出国(境)审批 </TITLE>");
			out.write("</HEAD>");
			out.write("<BODY>");
			XPathResult result = XMLUtil.parseConfig(doc, "//人员组成/*");
			Node node;
			while ((node =result.iterateNext()) != null) {
				String name = node.getAttributes().getNamedItem("姓名").getNodeValue();
				String gender = node.getAttributes().getNamedItem("性别").getNodeValue();
				String age = node.getAttributes().getNamedItem("年龄").getNodeValue();
				out.write("人员姓名: <input name=\"人员\" type=\"text\" value=\"" + name + "\"><br>");
				out.write("人员性别: <input name=\"人员\" type=\"text\" value=\"" + gender + "\"><br>");
				out.write("人员年龄: <input name=\"人员\" type=\"text\" value=\"" + age + "\"><br>");
			}
			out.write("</BODY>");
			out.write("</HTML>");
			out.flush();
			out.close();
		} else {
			return;
		}
	}
}
